# runtime: python37
# env: flex
runtime: python
env: flex

runtime_config:
    python_version: 3
# api_version: 1
# threadsafe: true

health_check:
  enable_health_check: True
  check_interval_sec: 5
  timeout_sec: 4
  unhealthy_threshold: 2
  healthy_threshold: 2
  
handlers:
- url: /.*
  script: auto

- url: /nltk.*
  script: auto